### ISSUE TITLE
How to upload a slug.tgz?

### ISSUE THREAD

**Issue by xeroxstar** [heroku/node-heroku-client#95]
Hello,

**I am trying to upload the slug file by following this tutorial (https://devcenter.heroku.com/articles/platform-api-deploying-slugs):**

```
let buf = require("fs").readFileSync(__dirname + "/slug.tgz");
let app = await heroku.post("/apps" , buf)
```

**the results are :**

```
{ acm: false,
  archived_at: null,
  buildpack_provided_description: null,
  build_stack:
   { id: '69bee368-352b-4bd0-9b7c-819d860a2588',
     name: 'heroku-18' },
  created_at: '2019-10-29T02:04:28Z',
  id: 'f6d4d110-dbe8-42e7-aef8-6b5416ed8231',
  git_url: 'https://git.heroku.com/calm-ocean-84625.git',
  maintenance: false,
  name: 'calm-ocean-84625',
  owner:
   { email: 'email@gmail.com',
     id: '63bb3b9a-6349-44e4-8cb4-ba54d6ee7b34' },
  region: { id: '59accabd-516d-4f0e-83e6-6e3757701145', name: 'us' },
  organization: null,
  team: null,
  space: null,
  internal_routing: null,
  released_at: '2019-10-29T02:04:28Z',
  repo_size: null,
  slug_size: null,
  stack:
   { id: '69bee368-352b-4bd0-9b7c-819d860a2588',
     name: 'heroku-18' },
  updated_at: '2019-10-29T02:04:28Z',
  web_url: 'https://calm-ocean-84625.herokuapp.com/' }
```

**then i try to release the app:**

```
heroku.post("/apps/" + app.name + "/releases", { slug: app.id })
 .then(app => { }) .catch(console.log);

```
**and i am getting this error:**

```
{ Error: Expected response to be successful, got 404
    at Request.handleFailure (@heroku\node_modules\heroku-client\lib\request.js:254:11)
    at concat.then (@heroku\node_modules\heroku-client\lib\request.js:148:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  statusCode: 404,
  body:
   { resource: 'slug',
     id: 'not_found',
     message: 'Couldn\'t find that slug.' } }
```

**what is wrong with my code? is there an example how to upload the slug file with this module?**

Thanks

**Comment by xeroxstar** [comment]
Nevermind, i figured it out, here is the code:

```
heroku
      .post("/apps",{name:'example'})
      .then(app => {
          let name = app.name;
          
          
          heroku.post("/apps/" + app.name + "/slugs", {
                body: {
                    process_types: {
                        web: "node-v0.10.20-linux-x64/bin/node web.js"
                    }
                }
            })
            .then( async app => {
                let id = app.id;
                
                await new Promise((x) => {
                    require('fs').readFile(__dirname + "/slug.tgz", function (err, data) {
                        if (err) return console.error(err);
                        request({
                            url  : app.blob.url,
                            body : data,
                            method: "PUT"
                        }, function (err, message,data) {
                            if (err) return console.error(err);
                            
                            console.log(data)
                            x()
                        });
                    })
                });
                
                heroku
                  .post("/apps/" + name + "/releases", {body:{ "slug": app.id }})
                  .then(app => {
                      
                      console.log(app);
                      
                  }).catch(console.log)
            })
})
```
